site_name: RbxNet
repo_name: GitHub
repo_url: https://github.com/roblox-aurora/rbx-net
nav:
    - Home: index.md
    - Installation:
        - Install for TypeScript: robloxts-install.md
        - Install for Lua: lua-install.md
    - Guide:
        - Events: events.md
        - Throttling: throttling.md
        - Caching: caching.md
        - Type Safety: type-safety.md
    - API Reference:
      - Net namespace: api-reference.md
      - Server Classes:
        - ServerEvent: class/NetServerEvent.md
        - ServerFunction: class/NetServerFunction.md
        - GlobalEvent: class/NetGlobalClientEvent.md
        - GlobalServerEvent: class/NetGlobalClientEvent.md
        - ServerAsyncFunction: class/NetServerAsyncFunction.md
      - Client Classes:
        - ClientEvent: class/NetClientEvent.md
        - ClientFunction: class/NetClientFunction.md
        - GlobalClientEvent: class/NetGlobalClientEvent.md
        - ClientAsyncFunction: class/NetClientAsyncFunction.md
theme:
    # feature:
    #  tabs: true
    name: material
    palette:
        primary: blue3
        accent: blue
    logo:
        icon: wifi
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.details:
    - pymdownx.inlinehilite:
    - pymdownx.tasklist:
    - pymdownx.critic:
    - pymdownx.tabbed:
    - pymdownx.superfences:
        preserve_tabs: true
        # legacy_tab_classes: true
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
extra_css:
  - 'styles/extra.css'
